# Configure Dependabot scanning.
version: 2

updates:
    # Check for updates to GitHub Actions.
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
      labels:
          - 'GitHub Actions'
          - 'Automated Testing'
          - '[Type] Build Tooling'
