dist: trusty

language: generic

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.jest-cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/.phpbrew

branches:
  only:
    - master

before_install:
  - nvm install

jobs:
  include:
    - name: JS unit tests
      env: WP_VERSION=latest
      before_install:
        - nvm install --latest-npm
      install:
        - npm ci
      script:
        - npm run build
        - npm run lint
        - npm run check-local-changes
        - npm run check-licenses
        - npm run test-unit -- --ci --maxWorkers=2 --cacheDirectory="$HOME/.jest-cache"

    - name: PHP unit tests (Docker)
      env: WP_VERSION=latest DOCKER=true
      script:
        - ./bin/run-wp-unit-tests.sh

    - name: PHP unit tests (PHP 5.6)
      language: php
      php: 5.6
      env: WP_VERSION=latest
      script:
        - ./bin/run-wp-unit-tests.sh
      if: branch = master and type != "pull_request"

    - name: PHP unit tests (PHP 5.3)
      env: WP_VERSION=latest SWITCH_TO_PHP=5.3
      script:
        - ./bin/run-wp-unit-tests.sh
      if: branch = master and type != "pull_request"

    - name: PHP unit tests (PHP 5.2)
      env: WP_VERSION=latest SWITCH_TO_PHP=5.2
      script:
        - ./bin/run-wp-unit-tests.sh

    - name: E2E tests (Admin with plugins) (1/2)
      env: WP_VERSION=latest SCRIPT_DEBUG=false POPULAR_PLUGINS=true
      install:
        - ./bin/setup-local-env.sh
      script:
        - $( npm bin )/wp-scripts test-e2e --config=./packages/e2e-tests/jest.config.js --listTests > ~/.jest-e2e-tests
        - npm run build
        - npm run test-e2e -- --ci --cacheDirectory="$HOME/.jest-cache" --runTestsByPath $( awk 'NR % 2 == 0' < ~/.jest-e2e-tests )

    - name: E2E tests (Admin with plugins) (2/2)
      env: WP_VERSION=latest SCRIPT_DEBUG=false POPULAR_PLUGINS=true
      install:
        - ./bin/setup-local-env.sh
      script:
        - $( npm bin )/wp-scripts test-e2e --config=./packages/e2e-tests/jest.config.js --listTests > ~/.jest-e2e-tests
        - npm run build
        - npm run test-e2e -- --ci --cacheDirectory="$HOME/.jest-cache" --runTestsByPath $( awk 'NR % 2 == 1' < ~/.jest-e2e-tests )

    - name: E2E tests (Author without plugins) (1/2)
      env: WP_VERSION=latest SCRIPT_DEBUG=false E2E_ROLE=author
      install:
        - ./bin/setup-local-env.sh
      script:
        - $( npm bin )/wp-scripts test-e2e --config=./packages/e2e-tests/jest.config.js --listTests > ~/.jest-e2e-tests
        - npm run build
        - npm run test-e2e -- --ci --cacheDirectory="$HOME/.jest-cache" --runTestsByPath $( awk 'NR % 2 == 0' < ~/.jest-e2e-tests )

    - name: E2E tests (Author without plugins) (2/2)
      env: WP_VERSION=latest SCRIPT_DEBUG=false E2E_ROLE=author
      install:
        - ./bin/setup-local-env.sh
      script:
        - $( npm bin )/wp-scripts test-e2e --config=./packages/e2e-tests/jest.config.js --listTests > ~/.jest-e2e-tests
        - npm run build
        - npm run test-e2e -- --ci --cacheDirectory="$HOME/.jest-cache" --runTestsByPath $( awk 'NR % 2 == 1' < ~/.jest-e2e-tests )
  allow_failures:
    - name: PHP unit tests (PHP 5.3)
      env: WP_VERSION=latest SWITCH_TO_PHP=5.3
      script:
        - ./bin/run-wp-unit-tests.sh
      if: branch = master and type != "pull_request"

    - name: PHP unit tests (PHP 5.2)
      env: WP_VERSION=latest SWITCH_TO_PHP=5.2
      script:
        - ./bin/run-wp-unit-tests.sh

