sudo: required

dist: trusty

language: php

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.phpbrew

before_install:
  - nvm install 6.11.1 && nvm use 6.11.1
  - npm install --global npm@5

jobs:
  include:
    - stage: unit
      php: 5.6
      script: composer install && ./vendor/bin/phpcs

    - stage: unit
      script:
        - npm install || exit 1
        - npm run ci || exit 1

    - stage: unit
      php: 7.1
      env: WP_VERSION=latest
      script:
        - ./bin/run-wp-unit-tests.sh

    - stage: unit
      php: 5.6
      env: WP_VERSION=latest
      script:
        - ./bin/run-wp-unit-tests.sh

    - stage: unit
      php: 7.1
      env: WP_VERSION=latest SWITCH_TO_PHP=5.3
      script:
        - ./bin/run-wp-unit-tests.sh

    - stage: unit
      php: 7.1
      env: WP_VERSION=latest SWITCH_TO_PHP=5.2
      script:
        - ./bin/run-wp-unit-tests.sh

    - stage: integration
      script:
        - npm install || exit 1
        - npm run build || exit 1
        - ./bin/run-e2e-tests.sh || exit 1

stages:
  - unit
  - integration

before_deploy:
  - npm install
  - cd docutron
  - npm install
  - cd ../
  - npm run docs-build

deploy:
  provider: surge
  project: ./docutron/build/
  skip_cleanup: true
  domain: gutenberg-devdoc.surge.sh
