version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg
      - ./packages/e2e-tests/plugins:/var/www/html/wp-content/plugins/gutenberg-test-plugins
      - ./packages/e2e-tests/mu-plugins:/var/www/html/wp-content/mu-plugins
    depends_on:
      - mysql

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg
    depends_on:
      - mysql
      - wordpress

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test

  wordpress_phpunit:
    image: chriszarate/wordpress-phpunit
    environment:
      PHPUNIT_DB_HOST: mysql
    volumes:
      - .:/app
      - testsuite:/tmp
    depends_on:
      - mysql

  composer:
    image: composer
    volumes:
      - .:/app

  wordpress_e2e_tests:
    image: wordpress
    ports:
      - 8889:80
    environment:
      WORDPRESS_DB_NAME: wordpress_e2e_tests
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress_e2e_tests:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg
      - ./packages/e2e-tests/plugins:/var/www/html/wp-content/plugins/gutenberg-test-plugins
      - ./packages/e2e-tests/mu-plugins:/var/www/html/wp-content/mu-plugins

  cli_e2e_tests:
    image: wordpress:cli
    volumes:
      - wordpress_e2e_tests:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg

volumes:
  testsuite:
  wordpress:
  wordpress_e2e_tests:
