name: End-to-End Tests

on:
    pull_request:
    push:
        branches:
            - trunk
            - 'release/**'
            - 'wp/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    e2e-playwright:
        name: Playwright - ${{ matrix.part }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4]
                totalParts: [4]

        steps:
            - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Npm build
              run: npm run build

            - name: Install Playwright dependencies
              run: |
                  npx playwright install chromium firefox webkit --with-deps

            - name: Install WordPress and start the server
              run: |
                  npm run wp-env start

            - name: Run the tests
              run: |
                  xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e:playwright -- --shard=${{ matrix.part }}/${{ matrix.totalParts }}

            - name: Archive debug artifacts (screenshots, traces)
              uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
              if: always()
              with:
                  name: failures-artifacts
                  path: artifacts/test-results
                  if-no-files-found: ignore

            - name: Archive flaky tests report
              uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
              if: always()
              with:
                  name: flaky-tests-report
                  path: flaky-tests
                  if-no-files-found: ignore
