name: Report Flaky Tests

on:
    workflow_run:
        workflows: ['End-to-End Tests', 'End-to-End Tests Playwright']
        types:
            - completed

jobs:
    report-to-issues:
        name: Report to GitHub issues
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
              with:
                  ref: trunk

            - name: Use desired version of NodeJS
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Npm install and build
              # We don't have to build the entire project, just the action itself.
              run: |
                  npm ci
                  npm run build:package-types

            - name: Report flaky tests
              uses: ./packages/report-flaky-tests
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  label: '[Type] Flaky Test'
                  artifact-name-prefix: flaky-tests-report
