name: OPTIONAL - Confirm if PHP changes require backporting to WordPress Core

on:
    pull_request:
        types: [opened, synchronize]
jobs:
    detect_php_changes:
        name: Detect PHP changes
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        steps:
            - name: Check out code
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
              with:
                  fetch-depth: 0
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Get changed PHP files
              id: changed-files-php
              uses: tj-actions/changed-files@716b1e13042866565e00e85fd4ec490e186c4a2f # v41.0.1
              with:
                  files: |
                      *.{php}
                      lib/**
                      phpunit/**

            - name: List all changed files
              if: steps.changed-files-php.outputs.any_changed == 'true'
              id: list-changed-php-files
              run: |
                  echo "Changed files:"
                  formatted_change_list=""
                  for file in ${{ steps.changed-files-php.outputs.all_changed_files }}; do
                    echo "$file was changed"
                    formatted_change_list+="<br>:grey_question: $file"
                  done
                  formatted_change_list+="<br>"
                  echo "formatted_change_list=$formatted_change_list" >> $GITHUB_OUTPUT

            - name: Find Comment
              uses: peter-evans/find-comment@v2
              id: find-comment
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: 'github-actions[bot]'
                  body-includes: '<!-- pr-contains-php-changes -->'

            - name: Create comment
              if: steps.find-comment.outputs.comment-id == '' && steps.changed-files-php.outputs.any_changed == 'true'
              uses: peter-evans/create-or-update-comment@v3
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      <!-- pr-contains-php-changes -->
                      This pull request has changed or added PHP files. Please confirm whether these changes need to be synced to WordPress Core, and therefore featured in the next release of WordPress.

                      If so, it is recommended to create a [new Trac ticket](https://core.trac.wordpress.org/newticket) and submit a pull request to the [WordPress Core Github repository](https://github.com/WordPress/wordpress-develop) soon after this pull request is merged.

                      If you're unsure, you can always ask for help in the #core-editor channel in  [WordPress Slack](https://make.wordpress.org/chat/).

                      Thank you! :heart:

                      <details>
                        <summary>View changed files</summary>
                        ${{ steps.list-changed-php-files.outputs.formatted_change_list }}
                      </details>

            - name: Update comment
              if: steps.find-comment.outputs.comment-id != '' && steps.changed-files-php.outputs.any_changed == 'true'
              uses: peter-evans/create-or-update-comment@v3
              with:
                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  edit-mode: replace
                  body: |
                      <!-- pr-contains-php-changes -->
                      This pull request has changed or added PHP files. Please confirm whether these changes need to be synced to WordPress Core, and therefore featured in the next release of WordPress.

                      If so, it is recommended to create a [new Trac ticket](https://core.trac.wordpress.org/newticket) and submit a pull request to the [WordPress Core Github repository](https://github.com/WordPress/wordpress-develop) soon after this pull request is merged.

                      If you're unsure, you can always ask for help in the #core-editor channel in  [WordPress Slack](https://make.wordpress.org/chat/).

                      Thank you! :heart:

                      <details>
                        <summary>View changed files</summary>
                        ${{ steps.list-changed-php-files.outputs.formatted_change_list }}
                      </details>

            - name: Update comment
              if: steps.find-comment.outputs.comment-id != '' && steps.changed-files-php.outputs.any_changed != 'true'
              uses: peter-evans/create-or-update-comment@v3
              with:
                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  edit-mode: replace
                  body: |
                      <!-- pr-contains-php-changes -->
                      This pull request changed or added PHP files in previous commits, but none have been detected in the latest commit.

                      Thank you! :heart:
