on:
    pull_request_target:
        types: [opened]
    push:
name: Pull request automation

jobs:
    pull-request-automation:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}
        strategy:
            matrix:
                node: ['14']

        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
              with:
                  ref: trunk

            - uses: ./.github/action/setup-node-env
              with:
                  node-version: ${{ matrix.node }}
                  install-working-directory: packages/project-management-automation

            - uses: ./packages/project-management-automation
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
