on:
    pull_request_target:
        types: [opened]
    push:
name: Pull request automation

jobs:
    pull-request-automation:
        runs-on: ubuntu-latest
        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
              with:
                  ref: trunk


            

            # Changing into the action's directory and running `npm install` is much
            # faster than a full project-wide `npm ci`.
            - run: |
                export NVM_DIR=~/.nvm
                source ~/.nvm/nvm.sh
                nvm install 16 && npm install -g npm@6
                cd packages/project-management-automation 
                npm install --loglevel verbose

            - uses: ./packages/project-management-automation
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
