on:
    pull_request_target:
        types: [opened]
    push:
name: Pull request automation

jobs:
    pull-request-automation:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}

        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
              with:
                  ref: revert-66270-revert-65681-managing-packages
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - uses: ./packages/project-management-automation
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
