on:
    pull_request_target:
        types: [opened]
    push:
name: Pull request automation

jobs:
    pull-request-automation:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}
        strategy:
            matrix:
                node: ['14']

        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.3.4
              with:
                  ref: trunk

            - name: Use desired version of NodeJS
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
              with:
                  node-version: ${{ matrix.node }}

            - name: Cache NPM packages
              uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ matrix.node }}-npm-pr-automation-cache-${{ hashFiles('**/package-lock.json') }}

            # Changing into the action's directory and running `npm install` is much
            # faster than a full project-wide `npm ci`.
            - name: Install NPM dependencies
              run: npm install
              working-directory: packages/project-management-automation

            - uses: ./packages/project-management-automation
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
