name: 'Mark issues stale after needs testing for 30 days'
on:
    schedule:
        - cron: '55 1 * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}
        steps:
            - uses: actions/stale@996798eb71ef485dc4c7b4d3285842d714040c4a # v3.0.17
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  days-before-stale: 30
                  days-before-close: -1
                  only-labels: 'Needs Testing'
                  skip-stale-issue-message: true
                  stale-issue-label: '[Status] Stale'
