name: 'Mark old issues as needs confirmation'
on:
    schedule:
        - cron: '45 1 * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@996798eb71ef485dc4c7b4d3285842d714040c4a # v3.0.17
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: "Hi,\nThis issue has gone 180 days without any activity. This means it is time for a check-in to make sure it is still relevant. If you are still experiencing this issue with the latest versions, you can help the project by responding to confirm the problem and by providing any updated reproduction steps.\nThanks for helping out."
                  days-before-stale: 180
                  days-before-close: -1
                  remove-stale-when-updated: false
                  stale-issue-label: 'Needs Testing'
