on:
  release:
    types: [released]

name: Upload Gutenberg plugin to WordPress.org plugin repo

jobs:
  upload:
    name: Upload Gutenberg Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out Gutenberg trunk from WP.org plugin repo
        env:
          PLUGIN_REPO_URL: 'https://plugins.svn.wordpress.org/gutenberg'
        run: svn checkout "$PLUGIN_REPO_URL/trunk"

      - name: Get previous stable tag
        id: get_previous_stable_tag
        env:
          STABLE_TAG_REGEX: 'Stable tag: [0-9]\+\.[0-9]\+\.[0-9]\+\s*'
        run: echo ::set-output name=stable_tag::$(grep "$STABLE_TAG_REGEX" ./trunk/readme.txt)

      - name: Delete everything
        working-directory: ./trunk
        run: find . -maxdepth 1 -not -name ".svn" -not -name "." -not -name ".." -exec rm -rf {} +

      - name: Download and unzip Gutenberg plugin asset into trunk folder
        env:
          PLUGIN_URL: ${{ github.event.release.assets[0].browser_download_url }}
        run: |
          curl -L -o gutenberg.zip $PLUGIN_URL
          unzip gutenberg.zip -d trunk
          rm gutenberg.zip

      - name: Replace the stable tag placeholder with the existing stable tag on the SVN repository
        env:
          STABLE_TAG_PLACEHOLDER: 'Stable tag: [0-9]\+\.[0-9]\+\.[0-9]\+\s*'
          STABLE_TAG: ${{ steps.get_previous_stable_tag.outputs.stable_tag }}
        run: sed -i "s/${STABLE_TAG_PLACEHOLDER}/${STABLE_TAG}/g" ./trunk/readme.txt

      - name: Commit the content changes
        working-directory: ./trunk
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          svn st | grep '^?' | awk '{print $2}' | xargs svn add
          svn st | grep '^!' | awk '{print $2}' | xargs svn rm
          echo "Committing version ${VERSION}"
          # svn commit -m "Committing version ${VERSION}"
